### ISSUE TITLE
Not working in IE11 or iOS <10

### ISSUE THREAD

**Issue by ErikEklund** [dolymood/vue-next-demo#1]
Hi! I'm looking to build a Vue3 project that needs to support older browsers. I stumbled across your polyfills that seem to be exactly what I need. Thanks for working on this!

We tried this demo site out in different browsers, but the current version (downloaded Sept 15) does not seem to render at all on IE 11 or below, or iOS <10 (it works on iOS 10, but not 8 or 9). Android seem to render fine from my tests so far.

Is the target compatibility still IE 9+ and iOS 8+? If yes, the polyfills / compatibility seems to be broken right now.

**Comment by dolymood** [comment]
My miss. Thanks for your issue.

I've fixed this bug, the core updated codes: https://github.com/dolymood/vue-next-demo/blob/master/src/main.ts#L2-L5

I tested on IE9, IE10, IE Edge, it works.

You can try it now.
