### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by ErikEklund** [dolymood/vue-next-demo#2]
I tried your demo site in different browsers, and it seemed to work as expected. I then added the polyfills to my own project, but could not get it to work. I noticed that to get it to work, I needed to copy your package.lock file and reinstall dependencies. I assume it tried to patch a package that has been updated so that the patch no longer works on a fresh install on vue3?

**Comment by dolymood** [comment]
I updated repo and used yarn.

npm i seems have some errors cased by diffent npm versions.
