### ISSUE TITLE
IE打开在线地址正常，拉代码编译启动则报错

### ISSUE THREAD

**Issue by XingXiaoWu** [dolymood/vue-next-demo#4]

**Comment by dolymood** [comment]
可以看下 patch pkg 的逻辑是否是正常的

**Comment by XingXiaoWu** [comment]
这。。。我看不太明白。。。

**Comment by XingXiaoWu** [comment]
从patch里的内容看是把const变var，箭头函数改function，但是整个vue-loader的修改会对代码造成什么影响，我本身没有预期，无法判断是否正常

**Comment by dolymood** [comment]
安装后 看看 yarn build 之后 试试行不行

**Comment by XingXiaoWu** [comment]
试过了，不行。无论是使用本仓库的代码，还是我新建demo去安装 vue-reactivity-polyfill或 vue3-plugin-polyfill，都是同样的@vue/reactive 报错

**Comment by XingXiaoWu** [comment]
因为现在没有windows电脑，不好截图错误。。。

**Comment by dolymood** [comment]
我本地重新 clone 然后 yarn 安装，然后serve 测试了 IE edge、10、9 都是没问题的

**Comment by XingXiaoWu** [comment]
![DFD6978E6B8E2B338245281C69FDA9DB](https://user-images.githubusercontent.com/22769131/112249138-36f3e700-8c92-11eb-9e33-6ef24dc2fc0b.png)

![7D76497E6FAF5DEE47AFC0457F1B0B20](https://user-images.githubusercontent.com/22769131/112248985-eaa8a700-8c91-11eb-8298-c96f2e23f0fd.png)
![6FA1916E4195A5782EDD240B633699F3](https://user-images.githubusercontent.com/22769131/112248993-eda39780-8c91-11eb-968b-71f6f48c1549.png)
![FAAF6B45DC83D6A1BC426DF73DFABF59](https://user-images.githubusercontent.com/22769131/112248999-f005f180-8c91-11eb-9327-720625f0197e.png)

拉取过程中提示依赖不对等warn

启动存在一些warn

IE11白屏

IE11报错

**Comment by XingXiaoWu** [comment]
切换到10，9也是相同的错误

**Comment by XingXiaoWu** [comment]
因为拉取过程中提示了依赖不对等，且报错为reactivity，我猜测可能与此有关。

但你重新拉取也正常，我猜测是否是你本地yarn的module缓存或者IE的缓存导致的运行正常或看起来运行正常。

**Comment by dolymood** [comment]
感觉是构建的问题
我是在MAC上运行的，然后到 windows 上访问预览的效果

我在windows上 clone 一个试试也

**Comment by XingXiaoWu** [comment]
啊这。。。那我要是上持续集成到linux上，又是另一翻景象就完蛋了。。

**Comment by dolymood** [comment]
参考 这个 commit https://github.com/dolymood/vue-next-demo/commit/871ae89b45a1ce5ed65e7db5d503c9a54489c31e
因为 @ vue/ xxx 这样的路径问题 ，windows 是 \\ ，这块我直接干掉了

**Comment by XingXiaoWu** [comment]
好，我明天用mac和linux编译试试，感谢

**Comment by XingXiaoWu** [comment]
mac下编译后在ie11-9访问正常，另外问一下，集成过程中，patches是必须的么

**Comment by dolymood** [comment]
是的 要不然是会报错的，所以才有patch，修改 const 和 箭头函数
